version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - pgadmin
    volumes:
      - ./yantar-shop-backend/src/main/resources/static:/yantar-shop-backend/src/main/resources/static

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: yantar-shop
    volumes:
      - ./data/yantar:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: yantar-shop@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80